PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX org:     <http://www.w3.org/ns/org#>
PREFIX regorg:   <https://www.w3.org/ns/regorg#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX person: <http://www.w3.org/ns/person#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

SELECT DISTINCT ?fractieUri ?voornaam ?familienaam ?start ?einde
WHERE {
  ?persoonUri a person:Person;
		persoon:gebruikteVoornaam ?voornaam;
  		foaf:familyName ?familienaam.

  ?mandatarisUri a mandaat:Mandataris;
				mandaat:isBestuurlijkeAliasVan ?persoonUri;
    			org:holds ?mandaatUri;
       			org:hasMembership [org:organisation ?fractieUri].

  ?mandaatUri a mandaat:Mandaat;
              org:role <http://data.vlaanderen.be/id/concept/BestuursfunctieCode/5ab0e9b8a3b2ca7c5e000013>.
  
  ?fractieUri regorg:legalName "Groen";
              org:memberOf ?bestuursOrgaanUri.
  
  ?bestuursorgaanInPeriodeUri a besluit:Bestuursorgaan ;
    org:hasPost ?mandaatUri .
  
  ?bestuursorgaanInPeriodeUri a besluit:Bestuursorgaan ;
    mandaat:isTijdspecialisatieVan ?bestuursorgaanUri ;
    mandaat:bindingStart ?start ;
    org:hasPost ?mandaatUri .

  OPTIONAL { ?bestuursorgaanInPeriodeUri mandaat:bindingEinde ?einde . }
  FILTER(?start >= "2019-01-01"^^xsd:date) 
}